{
 "title": "Git Commit by Day",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "author",
    "query": "SELECT DISTINCT author FROM \"gitlab-stat\".\"gitlab-history\" WHERE (time BETWEEN from_milliseconds($__timeFrom) AND from_milliseconds($__timeTo)) "
   },
   {
    "name": "group",
    "query": "SELECT DISTINCT \"group\" FROM \"gitlab-stat\".\"gitlab-history\" WHERE (time BETWEEN from_milliseconds($__timeFrom) AND from_milliseconds($__timeTo)) "
   },
   { "name": "period", "query": "1d,7d,30d" },
   {
    "name": "project",
    "query": "SELECT DISTINCT \"project\" FROM \"gitlab-stat\".\"gitlab-history\" WHERE (time BETWEEN from_milliseconds($__timeFrom) AND from_milliseconds($__timeTo)) "
   }
  ]
 },
 "panels": [
  { "title": "提交风格分析", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Daily Count per Author",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "database": "\"gitlab-stat\"",
     "measure": "additions",
     "rawQuery": "SELECT author, CREATE_TIME_SERIES(date, value) as LOC\nFROM (\n  SELECT BIN(time, $period) date, author, count(*) as value\n  FROM \"gitlab-stat\".\"gitlab-history\" \n  WHERE (time BETWEEN from_milliseconds($__timeFrom) AND from_milliseconds($__timeTo)) AND author IN ($author)\n      AND author != 'autogit'\n      AND parents = '1'\n      AND \"group\" in ($group)\n      AND project in ($project)\n  GROUP BY author, BIN(time, $period)\n  ORDER BY BIN(time, $period) DESC, author DESC)\nGROUP by author\nORDER BY sum(value) desc",
     "table": "\"gitlab-history\""
    }
   ]
  },
  {
   "title": "Daily Total Commit Size Per Author",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "database": "\"gitlab-stat\"",
     "measure": "additions",
     "rawQuery": "SELECT author, CREATE_TIME_SERIES(date, value) as LOC\nFROM (\n  SELECT BIN(time, $period) date, author, sum(measure_value::double) as value\n  FROM \"gitlab-stat\".\"gitlab-history\" \n  WHERE (time BETWEEN from_milliseconds($__timeFrom) AND from_milliseconds($__timeTo))\n     AND author IN ($author)\n     AND measure_name in ('additions', 'deletions')\n     AND parents = '1'\n     AND \"group\" in ($group)\n     AND project in ($project)\n     AND measure_value::double < 10000\n  GROUP BY author, BIN(time, $period)\n  ORDER BY BIN(time, $period) DESC, author DESC)\nGROUP by author\nORDER BY avg(value) DESC",
     "table": "\"gitlab-history\""
    }
   ]
  },
  {
   "title": "Commit Distribution During a Day",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "database": "\"gitlab-stat\"",
     "measure": "additions",
     "rawQuery": "WITH all_hours AS (\n  SELECT h FROM UNNEST(SEQUENCE(0, 23)) as t(h)\n)\nSELECT all_hours.h, CREATE_TIME_SERIES(data.date, value) hour\nFROM all_hours\nLEFT JOIN (\n  SELECT BIN(time, $period) date, (hour(time) + 8) % 24 h, count(*) AS value\n  FROM \"gitlab-stat\".\"gitlab-history\" \n  WHERE (time BETWEEN from_milliseconds($__timeFrom) AND from_milliseconds($__timeTo))\n     AND author IN ($author) AND author != 'autogit'\n     AND \"group\" IN ($group)\n     AND measure_name IN ('additions')\n    AND parents = '1'\n    AND project in ($project)\n  GROUP BY hour(time), BIN(time, $period)\n) AS data ON all_hours.h = data.h\nGROUP BY all_hours.h\nORDER BY all_hours.h",
     "table": "\"gitlab-history\""
    }
   ]
  },
  {
   "title": "选定用户的代码贡献分布",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "\"gitlab-stat\"",
     "measure": "FieldData",
     "rawQuery": "WITH all_hours AS (\n  SELECT h FROM UNNEST(SEQUENCE(0, 23)) as t(h)\n),\nuser_counts as (\nSELECT hour(time) as h, author, count(*) as c\nFROM \"gitlab-stat\".\"gitlab-history\" \nWHERE (time BETWEEN from_milliseconds($__timeFrom) AND from_milliseconds($__timeTo))\n    AND author IN ($author)\n    AND measure_name IN ('additions')\n    AND project in ($project)\n    AND \"group\" in ($group)\nGROUP BY hour(time), author\n)\nSELECT cast((all_hours.h + 8) % 24 as varchar) as \"时间\", sum(user_counts.c) as \"数量\"\nFROM all_hours\nLEFT JOIN user_counts ON all_hours.h = user_counts.h\nGROUP by (all_hours.h + 8) % 24\nORDER BY (all_hours.h + 8) % 24\n",
     "table": "\"devops-jira-new\""
    }
   ]
  }
 ]
}